# 'backup' file since this is just for notes; this file isn't needed for our development and production configuration

# Specify the containers/services that we want to create
services:
  node-app:
    build: .
    container_name: "node-app-c"
    ports:
      - "3000:3000"
    volumes:
      # Docker file for 'node-app' is in current directory
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env

    # Other way of doing environment variables
    # environment:
    #   - PORT=3000
