services:
  node-app:
    # You can pass arguments into the 'build' section
    build:
      # Just the location of the docker file, so '.' since it's in the same directory
      # as our docker-compose.yaml file'
      context: .

      # Here you can pass arguments that will be able in the dockerfile
      args:
        NODE_ENV: production

    # In our production environment we won't have any volumes

    # You'd change your environment variables for production
    # Note: if you're using secrets, then it's best you use .env files to avoid leaking them in your docker-compose.yaml files
    environment:
      - NODE_ENV=production

    # For production, we want to run the application like this; You could also do 'npm start'
    command: node index.js
