# Not actually used in development or production workflow, just for show and notes

# List our different services or containers
services:
  react-app:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
