# List our different services or containers
services:
  react-app:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: "react-app-dev-c"
    ports:
      # Expect vite's react dev server to be running on port 8080
      - 8080:8080
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.dev
