services:
  api:
    build:
      context: .

      # Runs both development stage and production stage which is good. Remember the former
      # builds the JavaScript files whilst the latter copies those files.
      # That should really be it for it
      target: production

    # No volumes here

    # Our port mapping
    ports:
      - 4000:4000

    # No need for commands since in the dockerfile we'll run the app
    # in production once the container starts.
